### ISSUE TITLE
How to print xml format of an object before posting to server

### ISSUE THREAD

**Issue by SindhuKonda** [Tickaroo/tikxml#101]
Before sending request to server, I Just want to check whether the data is formated as xml correctly or not.

For Example ::
For simple xml, we convert like below
            StringWriter writer = new StringWriter();
            serializer.write(object, writer);
            return writer.toString();

Can you please give an example of how to convert object to xml string using tikxml.

**Comment by WeaponMan** [comment]
Look at tests for example [this](https://github.com/Tickaroo/tikxml/blob/master/annotationprocessingtesting/src/test/java/com/tickaroo/tikxml/regressiontests/TeamTest.java)
