### ISSUE TITLE
TypeAdapter Not found exception

### ISSUE THREAD

**Issue by SindhuKonda** [Tickaroo/tikxml#102]
I am working on Android project.

@Xml(name = "Info")
public class Info {

    @Attribute(name="type")
    String type;
    @Attribute(name="id")
    String id;
    @Attribute(name = "date")
    String date;
}

**Added below dependencies in build file**
**--------------------------------------------------------------**
   compile "com.tickaroo.tikxml:annotation:0.8.13"
    compile "com.tickaroo.tikxml:core:0.8.13"
    annotationProcessor "com.tickaroo.tikxml:processor:0.8.13"

    compile 'com.squareup.retrofit2:retrofit:2.4.0'
    compile "com.tickaroo.tikxml:retrofit-converter:0.8.13"

**Added below proguard rules**
**------------------------------------------**
-keep class com.tickaroo.tikxml.** { *; }
-keep @com.tickaroo.tikxml.annotation.Xml public class *
-keep class **$$TypeAdapter { *; }

-keepclasseswithmembernames class * {
    @com.tickaroo.tikxml.* <fields>;
}
-keepclasseswithmembernames class * {
    @com.tickaroo.tikxml.* <methods>;
}

Still, Application is not generating Type adapter class for Info class.  Am I missing any thing else?

**Comment by sockeqwe** [comment]
Not sure if it's just a typo here on github but it's `@Xml` and not `@xml` ...

Also, please check if there is a `TypeAdapter` class  in `app/build/source/generated/apt/`.

**Comment by SindhuKonda** [comment]
Yeah its typo. Its `@Xml` only

I have checked in generated folder. but didn't find $$TypeAdapter class.

Do we need to specify any apt version?

**Comment by sockeqwe** [comment]
No.
Do you use any other annotation processing libraries like dagger or
butterknife? Are the generated files from those libraries there?

SindhuKonda <notifications@github.com> schrieb am Do., 20. Sep. 2018, 14:44:

**Comment by SindhuKonda** [comment]
Yes, I am using Dagger in my project

//Dagger dependencies
    compile 'com.google.dagger:dagger:2.2'
    apt "com.google.dagger:dagger-compiler:2.2"
    provided 'org.glassfish:javax.annotation:10.0-b28'
    compile 'javax.inject:javax.inject:1@jar'

Dagger related files are generated.

**Comment by WeaponMan** [comment]
Hmm... What will happen when you replace plugin android-apt with builtin android annotationProcessor?

**Comment by SindhuKonda** [comment]
Its working if we replace apt with annotationProcessor. Thank you.

**Comment by sockeqwe** [comment]
Yeah I actually thought that android gradle plugin 3.0 and above doesn't
work with android-apt anymore and doesnt build at all.

SindhuKonda <notifications@github.com> schrieb am Do., 20. Sep. 2018, 19:08:
