### ISSUE TITLE
Unescape  special characters in a string

### ISSUE THREAD

**Issue by shirishareddy** [Tickaroo/tikxml#111]
Hi,
 I have string in xml content with special characters using the escape characters like **&gt** , **&amp** etc. While converting the xml to java model i want to replace the escape characters with actual special characters. With simplexml it was by default, but with tikxml i am not able to achive this. 
Can someone help me with this? Do i need to write any type adapter for the string type?

Thanks,
Shirisha S.

**Comment by sockeqwe** [comment]
According to the [docs](https://github.com/Tickaroo/tikxml/blob/master/docs/AnnotatingModelClasses.md#type-converter) you have to `TypeConverter` ([there is already one](https://github.com/Tickaroo/tikxml/tree/master/converters/htmlescape) that seems to be what you are looking for).

```kotlin
new TikXml.Builder()
               .addTypeConverter(String.class, new HtmlEscapeStringConverter()) // HtmlEscapeStringConverter encode / decode html characters. This class ships as optional dependency
               .build();
```

and you also have to enable lookup for String.class in registered TypeConverters (which is not turned on per default for performance reasons) : 

```
apt {
    arguments {
        primitiveTypeConverters "java.lang.String"
    }
}
```

**Comment by shirishareddy** [comment]
Thanks for the quick reply Hannes :-)

**Comment by MukFlex** [comment]
I am unable to sync gradle after adding in App gradle. Please suggest what I am doing wrong.

**Issues-**
Could not find method apt() for arguments [build_bxwrhd14s0g8j7q0ajkmta3u5$_run_closure3@4ec1720b] on project ':app' of type org.gradle.api.Project.

**App level build.gradle**
 implementation  "com.tickaroo.tikxml:converter-htmlescape:$tikxml_version"

and 
apt {
    arguments {
        primitiveTypeConverters "java.lang.String"
    }
}

**Comment by sockeqwe** [comment]
Which version of tikxml do you use?

MukFlex <notifications@github.com> schrieb am Mi., 5. Feb. 2020, 09:07:

**Comment by MukFlex** [comment]
def tikxml_version = "0.9.3-SNAPSHOT"

**Comment by sockeqwe** [comment]
What project to you build? Android App?
It looks like `apt` is not included in your project
