### ISSUE TITLE
Nested XML Elements in file

### ISSUE THREAD

**Issue by svedie** [Tickaroo/tikxml#117]
Hello,

does this library supports nested/recursive elements?

For Example:
```
<category type="expenses" name="Verkehr" id="90" revisions="12">
	<category type="expenses" name="Auto" id="679" revisions="150"/>
	<category type="expenses" name="ÖPVN" id="678" revisions="150"/>
</category>
```
Greetings,
svedie

**Comment by sockeqwe** [comment]
Hello @svedie ,
yes, should work (never tried it before though). If not, let me know and we will fix it.

**Comment by svedie** [comment]
Thank you.

**Comment by svedie** [comment]
It works! 

Thanks for this library!
