### ISSUE TITLE
@PropertyElement with attribute

### ISSUE THREAD

**Issue by genaku** [Tickaroo/tikxml#118]
Is it possible to add attribute to PropertyElement? For example I need to put type of property element there:
```
<BODY>
	<LOGIN type="java.lang.String">mylogin</LOGIN>
	<TESTING type="java.lang.Boolean">true</TESTING>
</BODY>
```

**Comment by sockeqwe** [comment]
This is not valid xml. Can you give me a concrete example please? Did you
check @TextContent annotation?

Gennadiy Kuchergin <notifications@github.com> schrieb am So., 30. Dez.
2018, 19:23:

**Comment by genaku** [comment]
```
<?xml version='1.0' encoding='UTF-8' ?>
<BODY id="12">
	<LOGIN type="java.lang.String">mylogin</LOGIN>
	<TESTING type="java.lang.Boolean">true</TESTING>
</BODY>
```

**Comment by sockeqwe** [comment]
Do you want to read or write the attributes or are you asking i it is possible to skip attributes?

**Comment by genaku** [comment]
I need to write the attributes.

**Comment by genaku** [comment]
Ideal would be to write and read the attributes. But to write is priority.

**Comment by sockeqwe** [comment]
There are 2 options I think:
1. Use `@PropertyElement` and `@Attribute + @Path`:
```java
@Xml(name = "BODY")
class Body {
   @PropertyElement(name = "LOGIN") String loginValue;
   @Path("LOGIN") @Attribute(name = "type") String loginType;
   @PropertyElement(name = "TESTING") String testingValue;
   @Path("TESTING") @Attribute(name = "type") String testingType;
}
``` 

See [docs](https://github.com/Tickaroo/tikxml/blob/master/docs/AnnotatingModelClasses.md) or more details.

2. You can create a own class for `LOGIN` and `TESTING` and use `@TextContent` instead of `PropertyElement`:

```java
@Xml(name = "BODY")
class Body {
   @Element Login login;
   @Element Testing testing;
}
```

```java
@Xml
class Login {
  @TextContent String content;
  @Attribute(name ="type") String type
}
``` 

```java
@Xml
class Testing {
  @TextContent String content;
  @Attribute(name ="type") String type
}
``` 


Choose whatever solution you prefer
