### ISSUE TITLE
Cannot inherit from final TikXml

### ISSUE THREAD

**Issue by rsalomao2** [Tickaroo/tikxml#125]
Hi.

I got a project that use your library to convert XML. In the code there are a main class that Inhere from TikXml to converte the whole communication to XML. The problem is not compiling because it complain about "cannot inherit from final TikXml".
How can I manage that?

**Comment by sockeqwe** [comment]
You can and must not inherit from TikXml, why wod you inherit from it.

Rodrigo Salomao <notifications@github.com> schrieb am Fr., 1. Feb. 2019,
02:07:
