### ISSUE TITLE
Incorrect Artifact ID POM packaging 

### ISSUE THREAD

**Issue by iNoles** [Tickaroo/tikxml#130]
gradle.properties files on the processor common folder
it set to POM_ARTIFACT_ID = processor

gradle.properties on the processor folder
it set to POM_ARTIFACT_ID = processor-common

Would this confuses which one to call on kapt?

**Comment by sockeqwe** [comment]
Yes you were right, thanks for pointing this out!
Will create a new SNAPSHOT to see if things are working now again, Thanks!
