### ISSUE TITLE
How to initiate the lib in kotlin

### ISSUE THREAD

**Issue by XCarbone** [Tickaroo/tikxml#136]
I Understand that i have to create a class Model.
Then I can create a builder and build.
But where do i set the class model that have to be link to the builder ?
And where do i put the xml that i have to converte to the model?

**Comment by sockeqwe** [comment]
You get a TikXML instance like this:

```kotlin
val tikXml = TikXml.Builder()
                      .exceptionOnUnreadXml(true) // set this to false if you don't want that an exception is thrown
                      .build());
```

If you want to use it with Retrofit use the following dependency:

```
implementation 'com.tickaroo.tikxml:retrofit-converter:0.8.15'
```

and add

```kotlin
 val retrofit = Retrofit.Builder()
        .baseUrl(someUrl)
        .addConverterFactory(TikXmlConverterFactory.create())
        .build();
    service = retrofit.create(MyService::class);
```
