### ISSUE TITLE
XML  not generate in defined order

### ISSUE THREAD

**Issue by Mukesh1507** [Tickaroo/tikxml#142]
I am using tikxml library in kotlin. I have define a class to generate xml but tags not generate in sequence of order.

**Version- (Unable to upgrade version -0.8.15**
  implementation 'com.tickaroo.tikxml:annotation:0.8.13'
    implementation 'com.tickaroo.tikxml:core:0.8.13'
    implementation 'com.tickaroo.tikxml:retrofit-converter:0.8.13'
    kapt 'com.tickaroo.tikxml:processor:0.8.13'

Kotlin file - I had also tried with data class, but  generated xml is same

     @Xml(
       name = "soap:Envelope",
       writeNamespaces = ["xsi=http://www.w3.org/2001/XMLSchema-instance",
       "xsd=http://www.w3.org/2001/XMLSchema",
       "soap=http://schemas.xmlsoap.org/soap/envelope/"]
     )
    class HolidayRequest {
    @Path("soap:Header")
    @Element(name = "UserCredentials")
    var userDetail: UserCredentials= UserCredentials()

     @Path("soap:Body")
    @Element(name = "App_log")
    lateinit var appLog: AppLog

    @Path("soap:Body/Holiday_List")
    @PropertyElement(name = "param1")
    lateinit var param: String

    @Path("soap:Body/Holiday_List")
    @PropertyElement(name = "param2")
    lateinit var strDist: String
     }

Generated XML format sequence

        <?xml version="1.0" encoding="UTF-8"?><soap:Envelope 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">

            <soap:Header>
             <UserCredentials >
                
            </UserCredentials>
           </soap:Header>
          <soap:Body>
         <Holiday_List>
             
          </Holiday_List>
             <App_log>

             </App_log>
       </soap:Body>
       </soap:Envelope>

I need App_Log must be first tag in body section. 
Let me know that what I am doing wrong and what is the way to manage order.

**Comment by sockeqwe** [comment]
This should be fixed already but has not published yet. Could you please try to use  latest SNAPSHOT version? 

Add the snapshot repository to your main build.gradle

````
repositories {
  mavenCentral()
  maven {
    url 'http://oss.sonatype.org/content/repositories/snapshots'
  }
}
````

Then use `0.9.3-SNAPSHOT` versions i.e.

```
implementation 'com.tickaroo.tikxml:annotation:0.9.3-SNAPSHOT' 
```

**Comment by MukFlex** [comment]
@sockeqwe  Unable to sync snapshots version. I am getting below mention message.
Could not resolve com.tickaroo.tikxml:annotation:0.9.3-SNAPSHOT.
