### ISSUE TITLE
Parsing not work

### ISSUE THREAD

**Issue by Mukesh1507** [Tickaroo/tikxml#143]
Parsing not work. **outageInfoData**  is null. 

**1.Response-**
<?xml version="1.0" encoding="utf-8"?>
<DataSet xmlns="http://tempuri.org/">
    <xs:schema id="NewDataSet" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
       
    </xs:schema>
    <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
        <NewDataSet xmlns="">
            <Table1 diffgr:id="Table11" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                <OPEN_TIME>28-02-2020 10:00:00</OPEN_TIME>
                <SCHE_TIME>28-02-2020 14:40:00</SCHE_TIME>
                <CAUSE>PLANNED SHUTDOWN</CAUSE>
                <ID>P10022000280</ID>
                <MINUTES>195</MINUTES>
                <AREA_CODE>MANDAWALI FAZALPUR BLOCK B-JOSHI COLONY</AREA_CODE>
                <REASON>TRANSFORMER(MAINTENANCE ACTIVITY)</REASON>
            </Table1>
            <Table1 diffgr:id="Table12" msdata:rowOrder="1" diffgr:hasChanges="inserted">
                <OPEN_TIME>28-02-2020 10:00:00</OPEN_TIME>
                <SCHE_TIME>28-02-2020 14:40:00</SCHE_TIME>
                <CAUSE>PLANNED SHUTDOWN</CAUSE>
                <ID>P10022000280</ID>
                <MINUTES>195</MINUTES>
                <AREA_CODE>BLOCK B-JOSHI COLONY</AREA_CODE>
                <REASON>TRANSFORMER(MAINTENANCE ACTIVITY)</REASON>
            </Table1>      
        
         
        </NewDataSet>
    </diffgr:diffgram>
</DataSet>

2. Parser

import com.tickaroo.tikxml.annotation.Element
import com.tickaroo.tikxml.annotation.Path
import com.tickaroo.tikxml.annotation.Xml
@Xml
data class OutageResponse constructor(
    @Path("DataSet/diffgr:diffgram/NewDataSet")
    @Element(name = "Table1")
    val **outageInfoData** : List<OutageDetails>?)

//Outage Detail

import com.tickaroo.tikxml.annotation.PropertyElement
import com.tickaroo.tikxml.annotation.Xml
@Xml
data class OutageDetails constructor(
    @PropertyElement(name = "OPEN_TIME")
    var openTime: String? = null,
    @PropertyElement(name = "SCHE_TIME")
    var scheTime: String? = null,
    @PropertyElement(name = "CAUSE")
    var cause: String? = null,
    @PropertyElement(name = "ID")
    var id  : String? = null,
    @PropertyElement(name = "MINUTES")
    var minutes: String? = null,
    @PropertyElement(name = "AREA_CODE")
    var areaCode: String? = null,
    @PropertyElement(name = "REASON")
    var reason: String? = null )

**Comment by Bodo1981** [comment]
Hi @Mukesh1507 

can you tell me which version of tikxml you are using?

**Comment by MukFlex** [comment]
@Bodo1981  version - 0.9.3-SNAPSHOT

**Comment by Bodo1981** [comment]
please try the newest snapshot version 0.9.0_7-SNAPSHOT
-> sorry for the unconfenient versioning :-(
