### ISSUE TITLE
Type converter for inserting into database

### ISSUE THREAD

**Issue by mehranj73** [Tickaroo/tikxml#145]
I get this error when I want insert my object into database: 

> error: Cannot figure out how to save this field into database. You can consider adding a type converter for it. private com.mehranj73.spaceone.data.vo.Enclosure enclosure;

But I don't know how to write a convertor for my Entity for my own class.

```
@Entity(tableName = "image_of_the_day_table")
class ImageOfTheDayEntity (

     @PrimaryKey(autoGenerate = false)
     var pubdate: String,

     var title: String,
     var link: String,
     var description: String,

     var enclosure: Enclosure
)

class Enclosure {

    lateinit var url: String


    lateinit var length: String

    lateinit var type: String

}
```

**Comment by sockeqwe** [comment]
You have to annotate your Encloseure class with @XML as well

mehranj73 <notifications@github.com> schrieb am Do., 9. Apr. 2020, 12:13:

**Comment by mehranj73** [comment]
Sorry for opening an issue. I thinks it's just room problem but still I don't know how to fix it.
