### ISSUE TITLE
Problemas de parseo con dos objetos y arraylist dentro de cada uno HELP

### ISSUE THREAD

**Issue by JoseManuelAlvarez** [Tickaroo/tikxml#147]
Estoy tratando de implementar la librería de tikxml y todo bien hasta el punto donde tengo varias etiquetas y un objeto pero ya no funciona cuando agrego dos objetos estoy trabajando con android studio y usando la libreria de retrofit2 estas son las dependencias que uso
//retrofit2
    implementation 'com.squareup.retrofit2:retrofit:2.7.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.2.2'
    //TikXML
    implementation 'com.tickaroo.tikxml:annotation:0.8.13'
    implementation 'com.tickaroo.tikxml:core:0.8.13'
    annotationProcessor 'com.tickaroo.tikxml:processor:0.8.13'
    implementation 'com.tickaroo.tikxml:retrofit-converter:0.8.13'
    annotationProcessor 'com.tickaroo.tikxml:auto-value-tikxml:0.8.13'

este es la respuesta del servicio devolviendo un solo objeto

<?xml version="1.0"  encoding="utf-8"?>
<wsKPruebaServicio_response xmlns="wsKPruebaServicio">
    <token>e5b9b7230b2948590b6d28d36c613f70</token>
    <codigoOperacion>100</codigoOperacion>
    <QLO>
        <QLOTE>
            <LOT_FECHA>02/09/20</LOT_FECHA>
            <LOT_LOTE>300820</LOT_LOTE>
            <LOT_ENTRADA>2400</LOT_ENTRADA>
            <LOT_PESO>2450.36</LOT_PESO>
            <LOT_CODLOTE>562</LOT_CODLOTE>
        </QLOTE>
        <QLOTE>
            <LOT_FECHA>03/09/20</LOT_FECHA>
            <LOT_LOTE>010920</LOT_LOTE>
            <LOT_ENTRADA>2200</LOT_ENTRADA>
            <LOT_PESO>2500.36</LOT_PESO>
            <LOT_CODLOTE>563</LOT_CODLOTE>
        </QLOTE>
        <QLOTE>
            <LOT_FECHA>04/09/20</LOT_FECHA>
            <LOT_LOTE>040920</LOT_LOTE>
            <LOT_ENTRADA>2200</LOT_ENTRADA>
            <LOT_PESO>2200.36</LOT_PESO>
            <LOT_CODLOTE>564</LOT_CODLOTE>
        </QLOTE>
    </QLO>
    
</wsKPruebaServicio_response>

@Xml(name = "wsKPruebaServicio_response")
public class wsKPruebaServicio_response {

    @PropertyElement
    public String token;

    @PropertyElement
    public String codigoOperacion;

    @Element(name = "QLO")
    public QLO qlo;
}

@Xml(name = "QLO" )
public class QLO {
    @Element
    public List<QLOTE> qlote;
}

@Xml(name = "QLOTE")
public class QLOTE {

    @PropertyElement(name = "LOT_FECHA")
    public String FECHA;

    @PropertyElement(name = "LOT_LOTE")
    public String LOTE;

    @PropertyElement(name = "LOT_ENTRADA")
    public String ENTRADA;

    @PropertyElement(name = "LOT_PESO")
    public String PESO;

    @PropertyElement(name = "LOT_CODLOTE")
    public String CODLOTE;
}

Con sus getter and setter respectivos el caso es que hasta aqui si funciona pero si devuelvo 2 OBJETOS esta es la respuesta

<?xml version="1.0"  encoding="utf-8"?>
<wsKPruebaServicio_response xmlns="wsKPruebaServicio">
    <token>e5b9b7230b2948590b6d28d36c613f70</token>
    <codigoOperacion>100</codigoOperacion>
    <QLO>
        <QLOTE>
            <LOT_FECHA>01/09/20</LOT_FECHA>
            <LOT_LOTE>290820</LOT_LOTE>
            <LOT_ENTRADA>2200</LOT_ENTRADA>
            <LOT_PESO>2500.36</LOT_PESO>
            <LOT_CODLOTE>561</LOT_CODLOTE>
        </QLOTE>
        <QLOTE>
            <LOT_FECHA>04/09/20</LOT_FECHA>
            <LOT_LOTE>040920</LOT_LOTE>
            <LOT_ENTRADA>2200</LOT_ENTRADA>
            <LOT_PESO>2200.36</LOT_PESO>
            <LOT_CODLOTE>564</LOT_CODLOTE>
        </QLOTE>
    </QLO>
    <QLO2>
        <QLOTE2>
            <LOT2_FECHA>02/09/20</LOT2_FECHA>
            <LOT2_LOTE>300820</LOT2_LOTE>
            <LOT2_ENTRADA>2400</LOT2_ENTRADA>
            <LOT2_PESO>2450.36</LOT2_PESO>
            <LOT2_CODLOTE>562</LOT2_CODLOTE>
        </QLOTE2>
        <QLOTE2>
            <LOT2_FECHA>04/09/20</LOT2_FECHA>
            <LOT2_LOTE>040920</LOT2_LOTE>
            <LOT2_ENTRADA>2200</LOT2_ENTRADA>
            <LOT2_PESO>2200.36</LOT2_PESO>
            <LOT2_CODLOTE>564</LOT2_CODLOTE>
        </QLOTE2>
    </QLO2>
</wsKPruebaServicio_response>

basicamente hice lo mismo que cuadno devolvia un objeto 

@Xml(name = "wsKPruebaServicio_response")
public class wsKPruebaServicio_response {

    @PropertyElement
    public String token;

    @PropertyElement
    public String codigoOperacion;

    @Element(name = "QLO")
    public QLO qlo;

    @Element(name = "QLO2")
    public QLO2 qlo2;
}

pero ahora en la respuesta 

<-- 200 OK 
Date: Sat, 05 Sep 2020 16:55:14 GMT
D/OkHttp: Server: NetTalk-WebServer/8.71
D/OkHttp: Content-Type: text/xml
D/OkHttp: Set-Cookie: SESSIONID=j3eYcmgKMnwEfAs0BCf14XGmzLpdyd; path=/; HttpOnly
D/OkHttp: Connection: close
D/OkHttp: X-Frame-Options: sameorigin

java.io.EOFException: source exhausted prematurely 
me da como resulto esto

porfavor si alguien me puede orientar con mi error :/ para poder solucionarlo

**Comment by iNoles** [comment]
Esto es realmente cuando los bytes de los servidores tienen una longitud de contenido incorrecta. Puesto que usa retrofit, pruebe @Headers("Accept-Encoding: identity")

**Comment by JoseManuelAlvarez** [comment]
Hola buenas tardes muchas gracias por tomarte el tiempo en responderme si
me sirvió con los que me comentabas ya tenía más de un mes intentándolo y
sabía el por qué del error muchas gracias nuevamente!!!
