### ISSUE TITLE
Replace dangling readByte() calls with skip(long)

### ISSUE THREAD

**Issue by JakeWharton** [Tickaroo/tikxml#24]
For example, [this](https://github.com/Tickaroo/tikxml/blob/0ed58b3f25ed886cd04cfac5f58452bb5721afd1/core/src/main/java/com/tickaroo/tikxml/XmlReader.java#L552-L554) can be replaced with `skip(3)`. Not a functional change, but more semantically correct.

**Comment by sockeqwe** [comment]
Good catch ! Thanks!
