### ISSUE TITLE
Jack TypeConverter warning

### ISSUE THREAD

**Issue by iNoles** [Tickaroo/tikxml#31]
TypeConverter class com.tickaroo.tikxml.TypeConverter<T>.NoneTypeConverter must provide an empty (parameter-less) public constructor

**Comment by FabianTerhorst** [comment]
is it still working with jack, because there was a issue that the annotation processor couldn´t get access to the project folder with jack.

**Comment by iNoles** [comment]
if it is any apt plugin with jack, wouldn't work.

all I did with
```
compile 'com.tickaroo.tikxml:annotation:0.5.2-SNAPSHOT'
compile 'com.tickaroo.tikxml:core:0.5.2-SNAPSHOT'
annotationProcessor 'com.tickaroo.tikxml:processor:0.5.2-SNAPSHOT'
```

This is how I get that Jack warning for that.

**Comment by iNoles** [comment]
Since I fork it to correct that error, it also open another one. 

```java
Caused by: java.lang.NullPointerException: element == null
	at com.squareup.javapoet.Util.checkNotNull(Util.java:68)
	at com.squareup.javapoet.ClassName.get(ClassName.java:182)
	at com.tickaroo.tikxml.processor.generator.TypeAdapterCodeGenerator.generateCode(TypeAdapterCodeGenerator.kt:89)
```

**Comment by sockeqwe** [comment]
might be an issue of Jack in combination with Kotlin (annotation processor has been written in kotlin).

Unfortunately, I don't have time to investigate on this issue nor to add "official" support Jack right now

**Comment by sockeqwe** [comment]
Jack is deprecated. This issue is no longer relevant.
