### ISSUE TITLE
Extremely Odd Bugs 

### ISSUE THREAD

**Issue by iNoles** [Tickaroo/tikxml#35]
I was trying to parse this http://www.seminoles.com/rss.dbml?db_oem_id=32900&RSS_SPORT_ID=157113&media=news file. Somehow, I get the output RSS{newDBs=null}.

```java
@Xml
public class RSS {
	@Path("channel/item")
	@Element
	List<NewsDB> newDBs;

	@Override
	public String toString() {
		return "RSS{newDBs=" + newDBs + "}";
	}
}
```

```java
@Xml
public class NewsDB {
	@PropertyElement
	String title;

	@Override
	public String toString() {
		return "NewsDB{title = " + title + "}";
	}
}
```

**Comment by sockeqwe** [comment]
yes, there is a bug with `@Path` annotation which was introduced somewhen lately. I have also faced this kind of issue in our feeds. I'm working on a fix right now and you can expect to be fixed soon ...

**Comment by sockeqwe** [comment]
Actually, I think this is not a bug. You annotated it wrong ...

Should be `@Path("channel")` instead of `@Path("channel/item")` 

`@Path("channel/item") @Element List<NewsDB> newDBs;` means that there is a xml hierarchy like `/channel/item/NewsDB` which is not true, right?

```xml
 <channel>
    <title>
      <![CDATA[
					Florida State Seminoles
						Headline News

				]]>
    </title>
    <link>http://www.seminoles.com/</link>

    <description></description>
    <ttl>60</ttl>
    <category>Sports</category>

    <item>
      <title>Jimbo Fisher Presser Highlights: September 19</title>

      <pubDate>Mon, 19 Sep 2016 14:47:00 EST</pubDate>

      <link>http://www.seminoles.com//ViewArticle.dbml?DB_OEM_ID=32900&amp;ATCLID=211177837</link>
      <guid>http://www.seminoles.com//ViewArticle.dbml?DB_OEM_ID=32900&amp;ATCLID=211177837</guid>
      <description><![CDATA[Jimbo Fisher Presser Highlights: September 19]]></description>
      <category>

        <![CDATA[Football]]>
      </category>


      <enclosure url="http://image.cdnllnwnl.xosnetwork.com/pics33/400/JA/JAUEANIYWQMPSIR.20160919184235.jpg" length="18036" type="image/jpeg" />

    </item>

```

But an exception should be thrown I guess ...

**Comment by sockeqwe** [comment]
Actually it's not easy to check whether  (without performance issues) whether or not all annotated elements and attributes has been assigned ...

**Comment by iNoles** [comment]
I was trying to get all of the <item> elements like array inside of the channel element.

**Comment by sockeqwe** [comment]
See the docs, there is a concrete example of a so called inline list ... It
should work ...

https://github.com/Tickaroo/tikxml/blob/master/docs/AnnotatingModelClasses.md#list-of-elements

Jonathan <notifications@github.com> schrieb am Di., 20. Sep. 2016, 00:54:
