### ISSUE TITLE
can't handle array of primitives  

### ISSUE THREAD

**Issue by fangzhzh** [Tickaroo/tikxml#44]
The version I'm using is 
```
    compile 'com.tickaroo.tikxml:annotation:0.6.3-SNAPSHOT'
    compile 'com.tickaroo.tikxml:core:0.6.3-SNAPSHOT'

    apt 'com.tickaroo.tikxml:processor:0.6.3-SNAPSHOT'
```

Let's say I have a 

```
 <weatherForecast>
            <day>Wednesday</day>
            <temperature high="33" low="24" unit="Degrees Celsius"/>
            <day>Thursday</day>
            <temperature high="33" low="24" unit="Degrees Celsius"/>
            <day>Friday</day>
            <temperature high="34" low="25" unit="Degrees Celsius"/>
            <day>Saturday</day>
            <temperature high="33" low="24" unit="Degrees Celsius"/>
 </weatherForecast>
```

I'll define a WeatherForecast class
```
@Xml(name="weatherForecast")
    public static class WeatherForecast
    {
        @PropertyElement
        public String[] day;

        @Element
        public List<Temperature> temperature;

    }

    @Xml(name="temperature")
    public static class Temperature
    {
        @Attribute
        public String unit;

        @Attribute
        public String high;

        @Attribute
        public String low;

    }

```
For the WeatherForecast class, If I declare day as
-   `String[]`, can compile and run, get crash
    
    No TypeConverter found for type class [Ljava.lang.String;. You have to add one via TikXml.Builder().addTypeAdapter()

- `@PropertyElement
    List<String>`, can't compile 

   for  WeatherForecast$$TypeAdapter, compile error `value.day = config.getTypeConverter(java.util.List<java.lang.String>.class).read(reader.nextTextContent());`, `Error:(43, 80) error: <identifier> expected`

- `@Element
    List<String>`, can't compile 

  `Error:(186, 29) error`: The type java.lang.String used for field 'day' in weather.fangzhzh.com.weather.data.model.FourDays.WeatherForecast can't be used, because is not annotated with @Xml. Annotate java.lang.String with @Xml!

**Comment by sockeqwe** [comment]
Thanks for reporting. Arrays are inefficient because we have to know the size of the array, which means we have to read the whole xml document and store the values somewhere temporary (i.e. in a list) to know the final size of the array and then we have to copy the values from temporary structure into array.
Therefore, we don't have plans to support arrays. But at least an error message should be displayed in that case while compiling.

Nevertheless, `@PropertyElement List<String>` icon can't work. I assume you try to parse a xml like 

`@PropertyElement` always means read the text content like

```xml
<icon>a b c d e f</icon>
```

`@PropertyElement List<String> icon` means: convert the String `"a b c d e f"` somehow to a `List<String>`. TikXml cant know what a list item separator is. This could be solved by specifying a `TypeConverter` (see the docs).

The to group elements into a list is `@Element`, but you are right something like `@Element List<String> days` is not supported right now. Basically because we hadn't the need for that.
I have to evaluate how this could be implemented efficiently.

A possible workaround in the meantime would be

```java
class Day {
   @TextContent day;
}
```

and then use `@Element List<Day> days` rather then `@Element List<String> days`

**Comment by fangzhzh** [comment]
Hi, @sockeqwe 
I simplified my question class definition and changed the day to Class Day.
```
    @Xml(name="weatherForecast")
 public static class WeatherForecast
    {
         @Element
        public List<Day> days;

        @Element
        public List<Temperature> temperature;
    }
    @Xml(name="day")
    public static class Day{
        @TextContent
        String day;
    }
```
But I got empty string.

After a little trace, I found there might be a issue about Day$$TypeAdapter.fromXML.




```
public class Day$$TypeAdapter implements TypeAdapter<FourDays.Day> {
  public Day$$TypeAdapter() {
  }

  @Override
  public FourDays.Day fromXml(XmlReader reader, TikXmlConfig config) throws IOException {
    FourDays.Day value = new FourDays.Day();
    StringBuilder textContentBuilder = new StringBuilder();
    if (reader.hasAttribute()) {
      if (config.exceptionOnUnreadXml()) {
        throw new IOException("Could not map the xml attribute with the name '"+reader.nextAttributeName()+"' at path "+reader.getPath()+" to java class. Have you annotated such a field in your java class to map this xml attribute? Otherwise you can turn this error message off with TikXml.Builder().exceptionOnUnreadXml(false).build().");
      }
      while(reader.hasAttribute()) {
        reader.skipAttribute();
      }
    }
    while (reader.hasElement() || reader.hasTextContent()) {
      if (reader.hasElement()) {
        if (config.exceptionOnUnreadXml()) {
          throw new IOException("Could not map the xml element with the tag name '"+reader.nextElementName()+"' at path "+reader.getPath()+" to java class. Have you annotated such a field in your java class to map this xml attribute? Otherwise you can turn this error message off with TikXml.Builder().exceptionOnUnreadXml(false).build().");
        }
        while(reader.hasElement()) {
          reader.beginElement();
          reader.skipRemainingElement();
        }
      } else if (reader.hasTextContent()) {
        if (config.exceptionOnUnreadXml()) {
          throw new IOException("Could not map the xml element's text content at path '"+reader.getPath()+" to java class. Have you annotated such a field in your java class to map the xml element's text content? Otherwise you can turn this error message off with TikXml.Builder().exceptionOnUnreadXml(false).build().");
        }
        reader.skipTextContent();
      }
    }
    value.day = textContentBuilder.toString();
    return value;
  }

  @Override
  public void toXml(XmlWriter writer, TikXmlConfig config, FourDays.Day value) throws IOException {
  }
}

```

`textContentBuilder` is declared but never assigned. But at last we use its value.
Should we add one line `textContentBuilder.append(reader.nextTextContent());` above `reader.skipTextContent();`

**Comment by sockeqwe** [comment]
you are right, that is a bug I have introduced lately when I have changed the code generation. I will fix that right now. Thanks for your detailed feedback

**Comment by fangzhzh** [comment]
@sockeqwe Thanks 😊

**Comment by sockeqwe** [comment]
The `@TextContent` bug is fixed now in `0.6.4-SNAPSHOT`. I close this issue and will split this issue into two other issues  #47  (Error message for arrays) and #46 direct support for reading List<String>

**Comment by SindhuKonda** [comment]
On Latest also i.e 0.8.13, Can't we use @Element List<String> directly?

**Comment by SindhuKonda** [comment]
it is giving exception like **com.tickaroo.tikxml.TypeAdapterNotFoundException: No TypeAdapter for class java.lang.String found. Expected name of the type adapter is java.lang.String$$TypeAdapter**
