### ISSUE TITLE
Add option for ignoring not defined XML Tags

### ISSUE THREAD

**Issue by mzander** [Tickaroo/tikxml#49]
Hi,

first of all: thank you for the great library ;-)

Could you please add a possibility to skip those fields that are not defined within the pojo but are provideed by xml?
For now tikxml throws an io-exception.

thanks,
moritz

**Comment by sockeqwe** [comment]
Hi,
that is already possible.

```java
TikXml tikXml = TikXml.Builder()
                      .exceptionOnUnreadXml(false)
                      .build());


// With retrofit:
Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("https://example.com")
    .addConverterFactory(TikXmlConverterFactory .create(tikXml))
    .build();
```

**Comment by mzander** [comment]
I understood the method name as something different.

thanks!
