### ISSUE TITLE
Annotation API

### ISSUE THREAD

**Issue by sockeqwe** [Tickaroo/tikxml#5]
My proposal for the annotation API:

  1. Marking a class to be recognized by TikXml: Simple XML uses `@Root` annotation. In my oppinion not the best name, but we could use that one. Alternatively I purpose `@Xmlable`.

  ```java
@Root   // alternatively @Xmlable
class Foo { }
  ```
  produces and reads the following xml:
  ```xml
   <foo></foo>
  ```
  Simple xml's `@Root` [specification](http://simple.sourceforge.net/download/stream/report/cobertura/org.simpleframework.xml.Root.html) looks like this: `@Root( name = "foo", strict = true)` and I think we can use the same one. Howerver, I think we should set `strict` to false as default value (simple xml has true as default). This is compareable to jacksons `@IgnoreUnknownJsonProperties` and will throw an exception if there are unknown or unparsed data. What do you think?

  2. Attributes
 ```java
@Root   // alternatively @Xmlable
class Foo {
  @Attribute
  String a;

  @Attribute
  int b;
}
  ```
produces and reads the following xml:
  ```xml
   <foo a="something" b="123"></foo>
  ```

  Simple xml's `@Attribute(name="something", required = true, empty="default value if not parsed in feed)` [specification](http://simple.sourceforge.net/download/stream/report/cobertura/org.simpleframework.xml.Attribute.html)  From my point of view `@Attribute(required = true)` is in conflict with `@Root(strict = true)`. I would say, regadring kicker feeds, that nothing should be required per default and I would suggest to keep `@Attributes(required = true / false)` and `@Element(required = true / false)` and discharge `@Root(strict = false)`. What do you think?

  3. Inner elements
   ```java
  @Root   // alternatively @Xmlable
  class Foo {
  @Attribute
  String a;

   @Element Person person;
}

@Root
class Person {
   @Element String name;
   @Element int age;
}
  ```
produces and reads the following xml:
  ```xml
   <foo a="something">
      <person>
            <name>Hannes</name>
            <age>26</age>
      </person>
</foo>
  ```
  `@Element(name="something", required = true/false)` Simple XML [specification](http://simple.sourceforge.net/download/stream/report/cobertura/org.simpleframework.xml.Element.html) also provides `CDATA` support and `Class type(). While I would add CDATA support I'm not sure about the specific type. Reading  (parsing) xml is determined by the xml element name (i.e. `<foo>` maps to class `Foo`). However, when writing xml we might have explicitly specify which class to use to resolve polymorphism:
  ```java
  @Root
 class Foo {}
@Root 
 class Other extends Foo {} 

@Root
class Something {
   @Element 
    Foo foo;
}
```
The problem is that now ` something.foo = new Foo()` or ` something.foo = new Other()` . However the xml to write looks entirely different for `Foo` and `Other`. Hence we have to specify somehow an explicit type, or do you see a better solution?

  4. ElementList
  The Simple XML [specification](http://simple.sourceforge.net/download/stream/report/cobertura/org.simpleframework.xml.ElementList.html) looks good to me, especially `@ElementList(inline = true / false)`. However, we still have the same problem with polymorphism when writing xml as already discussed for a single element
  ```java
@Root
class Something {
   @ElementList List<Foo> foos;
}

something.foo.add(new Foo() );
something.foo.add(new Other() );
```

  Any good idea how to solve that issue? I think it can be estimated with annotation processing and `instanceof` while writing xml to an outputstream, but I'm not to sure about it. Any hint?

  5. XPath
  As you already now, there are still a lot of wrappers etc. in kicker feeds. Those can be "skipped" or virtually emulated with `@Path` annotation. I would use the same as Simple XML [specification](http://simple.sourceforge.net/download/stream/report/cobertura/org.simpleframework.xml.Path.html)

**Comment by Bodo1981** [comment]
1. und 2. @Root is good to go without "strict=false" because  all attributes should be per default "required=false" (you know kicker ^^)

3. no idea at the moment :)

4. i will think about it but for the moment instanceof was also my first thought

5. @Path VERY good for kicker feeds

**Comment by luke1313** [comment]
1. und 2. naming of @XmlAble or @Root - i dont care, strict and required should be false per default

3. simple xml isnt supporting polymorphism now - so we should annotate it anyway to define which class should be used per element (for example a type-string like in @JSONType)

4. @Path is just great.

**Comment by sockeqwe** [comment]
Regarding polymorphism, I think the following solution could work under the following assumption:

- Renaiming `@Root` to `@Xmlable` since the name root doesn't make sense anymore (see the next paragraph). We could also rename it to `@TikXml` to achieve a stronger Tickaroo branding ^^
- Each xml element name can be mapped to exactly one class
  In other words `<car>` maps to java `@Xmlable("car" ) class Car extends Vehicle {}` and  `<motorcycle>` maps to java `@Xmlable("motorcycle" ) class Motorcycle extends Vehicle {}` 

Therefore resolving polymorphism while reading the following xml should work:
```xml
<garage>
   <car id="1" />
  <motorcycle id="2" />
</garage>
```
```java
@Xmlable("garage")
class Garage {

      @ElementList(inline = true)
       List<Vehicle> inventar; // Will contain car and motorcycle
}
```

When writing xml we can do the other way arround. 
```java
for (Vehicle v : garage.inventar){
    if (v.getClass() == Car.class) {
        // write <car />
     }

    if (v.getClass() == Motorcycle.class) {
        // write <motorcycle />
     }

}
```

However, there is one issue with this approach: Since the xml element name will map to a class, we can not use the xml element name anymore to identify a "Property" (which btw. is another reason why xml is such a bad serialization format).
```xml
<person>
   <name>Hannes</name>
   <age>26</age>
</person>
```

```java
class Person {
    @Element
     String name;

     @Element
      int age;
}
```

The problem here is, that we would assume that `<name>` maps to a java `class Name {} `. Same for `<age>` which the compiler would expect to map to java `class Age {}`. For simple primitives  like String, int, double etc. our xml parser could make  an extra check and map them to the java field name rather than using xml elements name for determining the corresponding class. We could also introduce a special `@PropertyElement` annotation just for this kind of propertys to make it even more clear.

Than we could use `@Element` just for "objects" (not primitives) to resolve polymorphism like that:
```java
@Xmlable
class Garage {

 @Element
   Vehilce vehicle;
}
```

```xml
<garage>
   <car id="1" />
</garage>
```

or 

```xml
<garage>
   <motorcycle id="2" />
</garage>
```

Both xml snippets from above should be mappable to `Vehilce` by checking the xml element name as described with `@ElementList`


What do you think of this approach? 

Alternatively, if we don't want to use the xml element name as mapping indicator, we have to give the polymorphism information as suggested by @luke1313 via an additional annotation like `@JsonType` in jackson:

```java
@Xmlable
class Garage {

 @Element(type = { Car.class,  Motorcycle.class})
   Vehilce vehicle;
}
```
In this case the xml element name is mapped to the field, rather to the type and removes the problem of `@Element` on "Properties" as described above:
```java
class Person {
    @Element
     String name;

     @Element
      int age;
}
```

However, that requires to write more code because we have to use annotations to explicitly declare polymorphism types like `@Element(type = { Car.class,  Motorcycle.class})`. Last but not least, using xml element name for mapping to a field (and not as type information to map to a certain class) would also increase the extensibility of this xml parser, because we can add a "converter" to `java.util.Date` easily.


So the main question is: Is polymorphism more important than "properties" (like person name, person age)? The problem with properties is, that xml allow you to write properties as xml attributes and as child elements:

```xml
<person>
   <name>Hannes</name>
   <age>26</age>
</person>
```

vs.

```xml
<person name="Hannes" age="26" > </person>
```
Have I already mentioned how bad xml is for serializing data ^^ 
I'm not sure if replacing json with xml is a step forward for the kicker app ...

What do you think? What was your experience so far while working with kicker feeds? What about the home news feed? There is a lot of polymorphism I guess?

**Comment by luke1313** [comment]
i really like your approach mapping tags to classes - im thinking about cases where a class could (possibly) have more than one "name" coming from the backend in different feeds. i think this case exists and therefore we need a way to achieve mapping for multiple names per class.

i think we also could use it by extending the base class and just create classes per "name" - but thats kind of ugly - do you have any other ideas for the same objects coming with different names (if this actually happens in our feeds)

**Comment by sockeqwe** [comment]
Yep inheritance is the the only way to achieve that

or

Xml element name as property / field name

luke1313 <notifications@github.com> schrieb am Di., 15. Dez. 2015, 16:15:

**Comment by sockeqwe** [comment]
Ok, so I have written down a proposal for the annotation API. I'm not sure about it. Some parts of the API are inconsistent, but I don't know how to do it better way yet. XML is such a verbose format.

Inconsistency (maybe you find some more inconsistencies not listed here):

1. Regarding polymorphism, it's a mix of using xml element name as java class property and java class type to resolve polymorphism.
2. Especially `@ChildElement` vs. `@ChildElementList` (list has an inline option while `@ChildElement` has none), but do we really need two annotations for the similar thing? Can we use `@ChildElement` on Lists, if yes, what about inlining?
3. `@PropertyElement` vs. `@TextContent` (plus `@Path`)

See pull request #6 .
The proposal can be read here: https://github.com/Tickaroo/tikxml/blob/docs_annotation/docs/AnnotatingModelClasses.md (part of pull request)

What do you think about the name of the annotations?

**Comment by sockeqwe** [comment]
Since I have written down a proposal, let's close this issue and continue this discussion in a new issue #8
