### ISSUE TITLE
Mistake in compile-time error

### ISSUE THREAD

**Issue by Try4W** [Tickaroo/tikxml#54]
`
The class red.kometa.quest.common.entities.Paragraph.Part.Action.Way.NormalBehaviour is not annotated with @Xml, but is used in 'behaviour' in class @red.kometa.quest.common.entities.Paragraph.Part.Action.Way to resolve polymorphism. Please annotate @red.kometa.quest.common.entities.Paragraph.Part.Action.Way with @Xml
`

There is must be something like:
`Please annotate red.kometa.quest.common.entities.Paragraph.Part.Action.Way.NormalBehaviour with @Xml`

**Comment by sockeqwe** [comment]
> There is must be something like:
Please annotate red.kometa.quest.common.entities.Paragraph.Part.Action.Way.NormalBehaviour with @Xml

The current error message is basically just saying that (with some more details where this class is used: 
> The class `YourClass` is not annotated with `@Xml` but is used in `variableName` in `AnotherClass` to resolve polymorphism. Please annotate `YourClass` with `@Xml`

This is working as intended.

**Comment by Try4W** [comment]
Yeah pattern that you described is right. But look closer to message that I attached:

> The class `red.kometa.quest.common.entities.Paragraph.Part.Action.Way.NormalBehaviour` is not annotated with `@Xml`, but is used in `'behaviour'` in class `@red.kometa.quest.common.entities.Paragraph.Part.Action.Way` to resolve polymorphism. Please annotate `@red.kometa.quest.common.entities.Paragraph.Part.Action.Way` with `@Xml`

the same as
> The class `YourClass` is not annotated with `@Xml`, but is used in `variableName` in class `AnotherClass` to resolve polymorphism. Please annotate `YourClass` with `@Xml`

did I miss something?
