### ISSUE TITLE
@ElementNameMatcher does not support Integer

### ISSUE THREAD

**Issue by ened** [Tickaroo/tikxml#61]
This definition:

```
    @Element(
            typesByElement = {
                    @ElementNameMatcher(type = Integer.class)
            }
    )
    abstract List<Integer> values();
```

Will cause the compile error: 

> Error:(24, 17) error: Class java.lang.Integer used in @ElementNameMatcher must provide an public empty (parameter-less) constructor

**Comment by sockeqwe** [comment]
What exactly are you trying to do?

**Comment by ened** [comment]
Had a bunch of integers, like in this file:

```
<Response>
  <Cmd>1</Cmd>
  <Status>10</Status>
  <Cmd>1</Cmd>
  <Status>10</Status>
</Response>
```

Should result in a `List<Integer>` with contents `[1,10,1,10]`.

**Comment by sockeqwe** [comment]
I see, that is not supported right now. 

Duplicate #46, therefore I'm gonna close this issue. Please continue the discussion in #46
