### ISSUE TITLE
could you show the android sample project?

### ISSUE THREAD

**Issue by AlawnXu** [Tickaroo/tikxml#65]
could you show the android sample project?

**Comment by sockeqwe** [comment]
What do you mean with "the android sample"? Which sample are you referring
to?

AlawnXu <notifications@github.com> schrieb am Sa., 8. Apr. 2017, 11:58:

**Comment by WeaponMan** [comment]
I will create PR for example Java and Android project.

**Comment by sockeqwe** [comment]
That would be great. Please do it on your pull request "maven-to-gradle" (I
will accept it at the end of July)

Ondřej Kotora <notifications@github.com> schrieb am Mo., 19. Juni 2017 um
15:33 Uhr:
