### ISSUE TITLE
Provide way to mark Elements as optional

### ISSUE THREAD

**Issue by austenlux** [Tickaroo/tikxml#70]
I am unable to find a way that I can annotate a PropertyElement in a way that makes it optional.

Sometimes the field in my model class will not be present in the XML. So I would like a way to indicate to TikXML that that element/field is not required.

I understand that `.exceptionOnUnreadXml(false)` will prevent an exception from being thrown if an element exists in the XML that does not exist in the model class. But I have the opposite scenario. I need to prevent an exception from being thrown if an element exists in the model class, but does not appear in the XML.

**Comment by sockeqwe** [comment]
Not sure if I ve understood you correctly, can you give me a concrete
example and why you think it is not working with
.exceptionOnUnreadXml(false) ?

Austen <notifications@github.com> schrieb am Mi., 14. Juni 2017, 18:28:

**Comment by FabianTerhorst** [comment]
He has some attributes inside his pojo who are not always inside the xml.

**Comment by sockeqwe** [comment]
And in that case those attributes are the default value  like null for
objects, 0 for ints, false for boolean etc. in the parsed object. Otherwise
that is a bug of tikxml.

Fabian Terhorst <notifications@github.com> schrieb am Mi., 14. Juni 2017,
19:19:

**Comment by evant** [comment]
It seems like it might be a bug, out stacktrace is implying it's trying to parse a different tag as an int. I'll try to make a small test case the reproduces it.

**Comment by sockeqwe** [comment]
Which stacktrace? Are you working for the same company as @austenlux ? If yes, please post the stacktrace ...

**Comment by austenlux** [comment]
Sorry for the confusion. Yes, evant and I are working on the same issue. But we have found the problem somewhere else. It was actually just bad xml data, not a bug with TikXml.
Thanks for the speedy response though!

**Comment by sockeqwe** [comment]
Thanks for the clarification. Feel free to open an issue if the Exception Message (thrown because of bad xml data) was misleading.  Having clear error messages has high priority.
