### ISSUE TITLE
Unterminated comment at path /

### ISSUE THREAD

**Issue by Orbyt** [Tickaroo/tikxml#80]
I am receiving a response with the following structure:

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE response SYSTEM 'response.dtd'>
<response version='1.0'>
    <id>60</id>
    <errorcode>0</errorcode>
     <response>
         <result>
 	     <element>1</element>
 	     <errorcode>0</errorcode>
 	     <value>{&quot;links&quot;:{&quot;url&quot;:&quot;http://url.com&quot;},&quot;data&quot;:{&quot;no&quot;:null,&quot;id&quot;:&quot;someId&quot;}}</value>
        </result>
    </response>
</response>
```

The `value` element contains what is suppose to be JSON, containing a few properties such as `url`. Note that the example `url` provided above is not what is actually returned. Unfortunately as the URL contains sensitive data, I can not post it here. 

When this response is received, the following exception occurs:

```
java.io.IOException: Unterminated comment at path /
     at com.tickaroo.tikxml.XmlReader.syntaxError(XmlReader.java:848)
     at com.tickaroo.tikxml.XmlReader.nextNonWhitespace(XmlReader.java:808)
     at com.tickaroo.tikxml.XmlReader.doPeek(XmlReader.java:253)
     at com.tickaroo.tikxml.XmlReader.beginElement(XmlReader.java:326)
     at com.tickaroo.tikxml.TikXml.read(TikXml.java:110)
```

Here is a snippet of the relevant source code:

```
if (peek == '!' && fillBuffer(4)) {           
  // skip xml comments <!-- comment -->       
  // consume opening comment chars            
  buffer.readByte(); // '<'                   
  buffer.readByte(); // '!'                   
  buffer.readByte(); // '-'                   
  buffer.readByte(); // '-'                   
  if (!skipTo("-->")) {                       
    throw syntaxError("Unterminated comment");
  }

  // ...
}                                           
```

It appears that the parser thinks a comment begins somewhere in the response and attempts to skip it, however fails when it does not find a `String` matching `-->`.

I had planned to use a custom converter for the element containing the JSON, however the exception occurs before any of the code in the custom converter is called.

I do not see the beginning of a comment (`<!--`) anywhere in the response. Why is this exception occurring, and how can it be fixed?

**Comment by sockeqwe** [comment]
indeed, it seems that `<!DOCTYPE>` is not supported at the moment. Let me check if there is a easy solution for that.

**Comment by Orbyt** [comment]
@sockeqwe I've got a fork at https://github.com/Orbyt/tikxml which has a few commits that _seem_ to fix the issue. Let me know if my implementation is wrong.

**Comment by sockeqwe** [comment]
Thanks, yes I have something similar in mind. I should be able to fix this soon by just ignoring `<!DOCTYPE>`

**Comment by sockeqwe** [comment]
Fixed in `0.8.14-SNAPSHOT`

**Comment by Orbyt** [comment]
@sockeqwe Has `0.8.14-SNAPSHOT` been released? I see the commit for it but it doesn't appear to be online.

**Comment by sockeqwe** [comment]
It should be released.

```
0.8.14-SNAPSHOT    | Sat Mar 31 16:38:58 UTC 2018 
```

Source:
https://oss.sonatype.org/content/repositories/snapshots/com/tickaroo/tikxml/core/

Have you included the snapshot repository in your build.gradle file as described in the README.
