### ISSUE TITLE
Autovalue multiple namespaces

### ISSUE THREAD

**Issue by JuanFCalle** [Tickaroo/tikxml#81]
When i try to compile a class annotated with @AutoValue and @Xml with multiple namespaces.
<img width="578" alt="screen shot 2018-04-03 at 09 08 41" src="https://user-images.githubusercontent.com/1767516/38254567-3a7356f2-371f-11e8-9d2e-bc7331e23c73.png">
Produces the following error:
<img width="677" alt="screen shot 2018-04-03 at 09 15 37" src="https://user-images.githubusercontent.com/1767516/38254730-9e188a74-371f-11e8-9231-35653c22d370.png">
Its tying to close the curly braces each namespace.

**Comment by sockeqwe** [comment]
Thanks for reporting, I will take a look at it this week.

Btw. namespaces are only used for writing xml. namespaces are ignored for reading xml (if that is a temporarily workaround)

**Comment by WeaponMan** [comment]
Can we close this? It's fixed by #88

**Comment by sockeqwe** [comment]
Yep, thanks for the heads up!
