### ISSUE TITLE
TypeAdapterNotFoundException

### ISSUE THREAD

**Issue by zishanj** [Tickaroo/tikxml#82]
I am using this library with `Retrofit2` and receiving error: 

> com.tickaroo.tikxml.TypeAdapterNotFoundException: No TypeAdapter for class App

This my XML:
```
<?xml version="1.0" encoding="UTF-8"?>

<app>
    <version>5</version>
</app>
```

this is my `App` class for which I am expecting the converter to convert XML to this `App` object:
```
@Xml(name = "app")
public class App {
    @PropertyElement
    public int version;
}
```

I am building the Retrofit TikXML converter factory like this:
```
new Retrofit.Builder()
.addConverterFactory(TikXmlConverterFactory.create());
```

Here is the interface for `Retrofit` that calls the URL to fetch and parse data. I am using with `RxJava2`:
```
@GET("/apps/config.xml")
    Single<App> getApp();
```

Am I missing something?

**Comment by WeaponMan** [comment]
That's look like you forgot to add annotationProcessor to your gradle build file.

**Comment by zishanj** [comment]
I have these added in build.gradle:
```
implementation "com.tickaroo.tikxml:retrofit-converter:$tikxml_version"
implementation "com.tickaroo.tikxml:annotation:$tikxml_version"
```

what else is needed?

**Comment by WeaponMan** [comment]
This on android:
annotationProcessor "com.tickaroo.tikxml:processor:$tikxml_version"

**Comment by zishanj** [comment]
I have little concern about one issue. I am using `@Data` annotation from `lombok` which auto-generates getter and setter. If I use this annotation with my `App` class like this:

```
@Data
@Xml(name = "app")
public class App {
    @PropertyElement(name = "version")
    private int version;
}
```

I receive this compile-time error:

> The field 'version' in class com.test.common.viewmodel.apiservice.App has private or protected visibility. Hence a corresponding getter method must be provided with minimum package visibility (or public visibility if this is a super class in a different package) with the name getVersion() or isVersion() in case of a boolean. Unfortunately, there is no such getter method. Please provide one!

I was previously using `SimpleXML` Retrofit converter and it was never been an issue with it. Is there any workaround to this in `tikxml`?

**Comment by WeaponMan** [comment]
Change the access modifier on field "version" to `protected` and it will compile.

**Comment by zishanj** [comment]
No luck same error

**Comment by WeaponMan** [comment]
Then there are two options change it to public or get rid of @Data and generate own setters/getters. In SimpleXml this works because simplexml is using reflection at runtime.

**Comment by zishanj** [comment]
Hmm... Does reflection have some drawback due to which `tikxml` lacks this feature?

**Comment by WeaponMan** [comment]
Reflection is generally slower at runtime then generated code at compile time.
Every class you annotate with `@Xml` will have ClassName$$TypeAdapter generated at compile time.

**Comment by zishanj** [comment]
Thanks for your input.

**Comment by sockeqwe** [comment]
The problem is that annotation processing runs before lombok runs and tikxml annotation processor checks if there is a getter and setter method for a annotated property. TikXml annotation processor doesn't find one, because there is no such setter or getter at the time annotation processor runs because lombok runs afterwards (actually manipulates jvm bytecode).

We could (theoretically) write a universal TypeAdapter that uses Reflection (rather than annotation processing and the generated TypeAdapter) but this is not on our TODO list for now...

Nevertheless, if you would like to spend some time to write such a type adapter (reflection based) I'm more than happy to add a link to your type adapter.

**Comment by zishanj** [comment]
Try this in your proguard:

`-keep class **$$TypeAdapter { *; }`

**Comment by zishanj** [comment]
otherwise check this similar issue [83](https://github.com/Tickaroo/tikxml/issues/83) to mine and add this line also in proguard:

`-keep @com.tickaroo.tikxml.annotation.Xml public class *`

**Comment by WeaponMan** [comment]
@zishanj I don't think this is same issue 
@elghrabi Can you post some example code and build.gradle with this issue?

**Comment by WeaponMan** [comment]
@elghrabi I suppose you are doing something like this:
```java
TikXml xml = new TikXml.Builder().build();
String text = xml.read(okioBuffer, String.class);
```
Which make no sense to me, why your are using this library for reading String as root element.
Maybe I am wrong. I am just guessing.
