### ISSUE TITLE
Proguard rule for TypeAdapter does not work

### ISSUE THREAD

**Issue by zishanj** [Tickaroo/tikxml#83]
I am receiving this error when running `release` version of the app which compiles with proguard:

> com.tickaroo.tikxml.TypeAdapterNotFoundException: No TypeAdapter for class com.sample.common.viewmodel.apiservice.a found. Expected name of the type adapter is com.sample.common.viewmodel.apiservice.a$$TypeAdapter

As per your documentation, I have added this in Proguard:

```
-keep class com.tickaroo.tikxml.** { *; }
-keep class **$$TypeAdapter { *; }
-keepclasseswithmembernames class * {
    @com.tickaroo.tikxml.* <fields>;
}
-keepclasseswithmembernames class * {
    @com.tickaroo.tikxml.* <methods>;
}
```

This app works fine when running in `debug` mode with Proguard disabled.

**Comment by zishanj** [comment]
Here is my converter class:

```
@Xml(name = "app")
public class App {
    @PropertyElement(name = "version")
    public int version;
}
```

which I use with Retrofit2. While created Retrofit2 service, I have only added this `converterFactory`:

`builder.addConverterFactory(TikXmlConverterFactory.create());`

**Comment by WeaponMan** [comment]
You will need another rule for keeping class names for classes that you annotated with `@Xml`... I guess.

**Comment by zishanj** [comment]
What exactly is that rule?

**Comment by zishanj** [comment]
I thought this rule will be sufficient to solve this TypeAdapter error:

`-keep class **$$TypeAdapter { *; }`

**Comment by WeaponMan** [comment]
Maybe this I am not that familiar with proguard.
`-keep @com.tickaroo.tikxml.annotation.Xml public class *`
The problem is that generated adapter will be `App$$TypeAdapter` a then proguard runs and App class will be `a` and at runtime type adapter will looked up with name 'a$$TypeAdapter` that will not exist.

**Comment by zishanj** [comment]
I have manually excluded my class `App` with this rule:

`-keepnames class com.sample.common.viewmodel.apiservice.App`

and it works.

**Comment by zishanj** [comment]
This proguard rule should also be included in Readme. Thanks!

**Comment by sockeqwe** [comment]
Wanna send a pull request?

zishanj <notifications@github.com> schrieb am Mi., 11. Juli 2018, 12:03:
