### ISSUE TITLE
How can I get PropertyElement form tag with attribue

### ISSUE THREAD

**Issue by SeleznevAM** [Tickaroo/tikxml#85]
How can I get PropertyElement form tag with attribue
`<MediaFile height="396" width="600" bitrate="496" type="video/x-flv" delivery="progressive"><![CDATA[http://media.scanscout.com/ads/partner1_a1d1fbbc-c4d4-419f-b6c8-e9db63fd4491.flv]]></MediaFile>`
Attributes i get normal, but CDATA i can't get.

**Comment by WeaponMan** [comment]
With `@TextContent` annotation.

**Comment by SeleznevAM** [comment]
Thanks
