### ISSUE TITLE
Arabic language support

### ISSUE THREAD

**Issue by alihasan95** [Tickaroo/tikxml#86]
When the data request library does not return the Arabic language text but returns HTML encoding

**Comment by sockeqwe** [comment]
I don't fully understand the problem and how arabic language and how it is
related to html but as long as the file you try to parse  is UTF-8 TikXml
is able to parse it.

As far as I know arabic language is completely covered by UTF-8

ali hasan <notifications@github.com> schrieb am Fr., 27. Juli 2018, 14:37:

**Comment by sockeqwe** [comment]
Closed because inactive and not a bug imho as arabic language should be supported out of the box if your source is UTF-8
