### ISSUE TITLE
Getting error while using writeNamespaces

### ISSUE THREAD

**Issue by SindhuKonda** [Tickaroo/tikxml#99]
Hi,
I am getting error like **@Xml annotated class Event contains an illegal namespace definition: default.com because it contains more than 1 equals sign (=) character** for below code :

@Xml(writeNamespaces={"default.com"}, name="Event")
public class Event {
   
   @Attribute(name="id")
    private String id;
}

**Comment by WeaponMan** [comment]
This error was fixed in #87, but not yet released. If you don't have time to wait for new release I recommend cloning `master` and installing it locally.

**Comment by sockeqwe** [comment]
Yeah, i'm still struggeling with releasing a new version. Sorry about that, will take a look at it this evening. In the meantime you can also use latest `snapshot` (see readme) that is basically `master` branch.

**Comment by SindhuKonda** [comment]
Thank you for quick response. 
I am very new to this tikXml. I am using tikXml for my **android** project. I have some basic questions. Can you please clarify.

1. I Am adding below dependencies in my gradle file. To work with tikxml, these dependencies are sufficient or do i need any other dependencies ?
For tikxml
implementation 'com.tickaroo.tikxml:annotation:0.8.13'
implementation 'com.tickaroo.tikxml:core:0.8.13'
annotationProcessor 'com.tickaroo.tikxml:processor:0.8.13'

For retrofit : 
implementation 'com.tickaroo.tikxml:retrofit-converter:0.8.13'

2. What is snapshot? Do i need to add snapshot dependency also?
3. In Simple xml, we use InputNode and elements etc. to iterate through nodes. In document It was provided like tikXml uses type adapter for parsing. Can you please give sample code that how to iterate through nodes using type adapters?
4. Is there any annotation in tikXml that replaces simple xml Matcher?  

Sorry for basic questions but please clarify. it helps alot for my coding. Thanks in advance.

**Comment by WeaponMan** [comment]
1) I recommend using version variable in `build.gradle` and keeping TikXml all dependencies same version.
```groovy
def tikXmlVersion = "0.8.13"
dependencies {
   implementation "com.tickaroo.tikxml:annotation:$tikXmlVersion"
   implementation "com.tickaroo.tikxml:core:$tikXmlVersion"
   implementation "com.tickaroo.tikxml:retrofit-converter:$tikXmlVersion"
   annotationProcessor "com.tickaroo.tikxml:processor:$tikXmlVersion"
}
```
2) Snapshot is "unstable" build of current master branch. More in readme.

3 - 4) Take a look [here](https://github.com/Tickaroo/tikxml/blob/master/docs/AnnotatingModelClasses.md)

**Comment by WeaponMan** [comment]
I see, you are looking for dom api, right? You can use bare `XmlReader` in core. The thing is this project is not focused on dom api, but this is all about parsing xml elements into Pojo classes. TypeAdapters for annotated classes with `@Xml` are created at compile time, you can look at those for figuring out how to use `XmlReader`.
